### ISSUE TITLE
Add Merch page to the site

### ISSUE THREAD

**Issue by LaputanMachines** [LaputanMachines/MikesGamingTrove#47]
Add a Merch page to the site. Page should show image previews of all products sold. Buttons would all redirect to the real online merch store. Should also set up a merch store as well. Sell the following:

- T-shirts with the MGT logo or the MGT banner pattern
- Stickers with the MGT banner pattern
- Enamel pins of the MGT logo and deep cuts from the site's content

Important that the image previews match the existing UI of the site; it would be confusing to introduce another website's UI into MGT.

**Comment by FlatlanderWoman** [comment]
https://snipcart.com/blog/jekyll-ecommerce-tutorial

Found out that Snipcart can enable you to sell merch via Jekyll while taking a 2% cut of transactions. Implement this and sell stickers and enamel pins and stuff.
